# Generated by Django 5.0 on 2024-02-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_commentmodel_users_commentmodel_usercomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='userComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
