# Generated by Django 5.0 on 2024-02-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_commentmodel_usercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='userComment',
            new_name='profile',
        ),
    ]
